# Use postgres/example user/password credentials
version: '3.1'

services:


  # Spin up and set up the Postgres instance
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"
